query BinderByShortId(
  $shortId: String!
  $cardFirst: Int!
  $cardOffset: Int!
  $cardOrderBy: [BinderCardsOrderBy!]!
  $cardFilter: BinderCardsFilter
  $includeFilteredTotalCount: Boolean!
) {
  binderByShortId(binderShortId: $shortId) {
    id
    nodeId
    name
    note
    ownerId
    shortId
    tcgId
    visibility
    binderCardCount
  }
  binderCardsByShortId(
    binderShortId: $shortId
    first: $cardFirst
    offset: $cardOffset
    orderBy: $cardOrderBy
    filter: $cardFilter
  ) {
    totalCount @include(if: $includeFilteredTotalCount)
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        ...BinderCardSummaryFields
      }
    }
  }
}
