/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {};
export var BinderVisibility;
(function (BinderVisibility) {
    BinderVisibility["Listed"] = "listed";
    BinderVisibility["Private"] = "private";
    BinderVisibility["Unlisted"] = "unlisted";
})(BinderVisibility || (BinderVisibility = {}));
export var CardCondition;
(function (CardCondition) {
    CardCondition["Excellent"] = "excellent";
    CardCondition["Good"] = "good";
    CardCondition["LightPlayed"] = "light_played";
    CardCondition["Mint"] = "mint";
    CardCondition["NearMint"] = "near_mint";
    CardCondition["Played"] = "played";
    CardCondition["Poor"] = "poor";
})(CardCondition || (CardCondition = {}));
export var CurrencyCode;
(function (CurrencyCode) {
    CurrencyCode["Eur"] = "EUR";
    CurrencyCode["Gbp"] = "GBP";
    CurrencyCode["Jpy"] = "JPY";
    CurrencyCode["Thb"] = "THB";
    CurrencyCode["Usd"] = "USD";
})(CurrencyCode || (CurrencyCode = {}));
export var FilterIs;
(function (FilterIs) {
    FilterIs["NotNull"] = "NOT_NULL";
    FilterIs["Null"] = "NULL";
})(FilterIs || (FilterIs = {}));
export var LanguageCode;
(function (LanguageCode) {
    LanguageCode["Ar"] = "ar";
    LanguageCode["De"] = "de";
    LanguageCode["En"] = "en";
    LanguageCode["Es"] = "es";
    LanguageCode["Fr"] = "fr";
    LanguageCode["Grc"] = "grc";
    LanguageCode["He"] = "he";
    LanguageCode["It"] = "it";
    LanguageCode["Ja"] = "ja";
    LanguageCode["Ko"] = "ko";
    LanguageCode["La"] = "la";
    LanguageCode["Ph"] = "ph";
    LanguageCode["Pt"] = "pt";
    LanguageCode["Qya"] = "qya";
    LanguageCode["Ru"] = "ru";
    LanguageCode["Sa"] = "sa";
    LanguageCode["Zhs"] = "zhs";
    LanguageCode["Zht"] = "zht";
})(LanguageCode || (LanguageCode = {}));
export var MarketPriceSource;
(function (MarketPriceSource) {
    MarketPriceSource["Cardkingdom"] = "cardkingdom";
    MarketPriceSource["Cardmarket"] = "cardmarket";
    MarketPriceSource["Tcgplayer"] = "tcgplayer";
})(MarketPriceSource || (MarketPriceSource = {}));
export var MtgColor;
(function (MtgColor) {
    MtgColor["B"] = "B";
    MtgColor["C"] = "C";
    MtgColor["G"] = "G";
    MtgColor["R"] = "R";
    MtgColor["U"] = "U";
    MtgColor["W"] = "W";
})(MtgColor || (MtgColor = {}));
/** Defines a per-field sorting order */
export var OrderByDirection;
(function (OrderByDirection) {
    /** Ascending order, nulls first */
    OrderByDirection["AscNullsFirst"] = "AscNullsFirst";
    /** Ascending order, nulls last */
    OrderByDirection["AscNullsLast"] = "AscNullsLast";
    /** Descending order, nulls first */
    OrderByDirection["DescNullsFirst"] = "DescNullsFirst";
    /** Descending order, nulls last */
    OrderByDirection["DescNullsLast"] = "DescNullsLast";
})(OrderByDirection || (OrderByDirection = {}));
export var OrganizationMemberRole;
(function (OrganizationMemberRole) {
    OrganizationMemberRole["Admin"] = "ADMIN";
    OrganizationMemberRole["Member"] = "MEMBER";
    OrganizationMemberRole["Owner"] = "OWNER";
})(OrganizationMemberRole || (OrganizationMemberRole = {}));
export const BinderByShortIdDocument = gql `
    query BinderByShortId($shortId: String!) {
  binderByShortId(binderShortId: $shortId) {
    id
    nodeId
    name
    shortId
  }
}
    `;
/**
 * __useBinderByShortIdQuery__
 *
 * To run a query within a React component, call `useBinderByShortIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useBinderByShortIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBinderByShortIdQuery({
 *   variables: {
 *      shortId: // value for 'shortId'
 *   },
 * });
 */
export function useBinderByShortIdQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(BinderByShortIdDocument, options);
}
export function useBinderByShortIdLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(BinderByShortIdDocument, options);
}
export const CardSearchDocument = gql `
    query CardSearch($query: String!, $first: Int = 8) {
  cardsCollection(
    first: $first
    filter: {tcgId: {eq: "mtg"}, name: {ilike: $query}}
    orderBy: [{releasedAt: DescNullsLast}, {name: AscNullsLast}]
  ) {
    edges {
      node {
        id
        externalId
        name
        collectorNumber
        rarity
        finishes
        imageSmallUrl
        imageNormalUrl
        releasedAt
        cardSet {
          id
          code
          name
          releaseAt
        }
        marketPrices(first: 8, orderBy: [{source: AscNullsLast}]) {
          edges {
            node {
              source
              finish
              amount
              currency
              priceDate
            }
          }
        }
      }
    }
  }
}
    `;
/**
 * __useCardSearchQuery__
 *
 * To run a query within a React component, call `useCardSearchQuery` and pass it any options that fit your needs.
 * When your component renders, `useCardSearchQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCardSearchQuery({
 *   variables: {
 *      query: // value for 'query'
 *      first: // value for 'first'
 *   },
 * });
 */
export function useCardSearchQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CardSearchDocument, options);
}
export function useCardSearchLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CardSearchDocument, options);
}
export const CreateBinderDocument = gql `
    mutation CreateBinder($name: String!, $tcgId: String = "mtg") {
  insertIntoBindersCollection(objects: [{name: $name, tcgId: $tcgId}]) {
    records {
      id
      nodeId
      name
      shortId
    }
  }
}
    `;
/**
 * __useCreateBinderMutation__
 *
 * To run a mutation, you first call `useCreateBinderMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateBinderMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createBinderMutation, { data, loading, error }] = useCreateBinderMutation({
 *   variables: {
 *      name: // value for 'name'
 *      tcgId: // value for 'tcgId'
 *   },
 * });
 */
export function useCreateBinderMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(CreateBinderDocument, options);
}
export const CurrentUserOrganizationContextsDocument = gql `
    query CurrentUserOrganizationContexts {
  currentUserOrganizationContexts {
    edges {
      node {
        organizationId
        role
        organization {
          id
          name
        }
      }
    }
  }
}
    `;
/**
 * __useCurrentUserOrganizationContextsQuery__
 *
 * To run a query within a React component, call `useCurrentUserOrganizationContextsQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserOrganizationContextsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserOrganizationContextsQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserOrganizationContextsQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CurrentUserOrganizationContextsDocument, options);
}
export function useCurrentUserOrganizationContextsLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CurrentUserOrganizationContextsDocument, options);
}
export const CurrentUserProfileDocument = gql `
    query CurrentUserProfile {
  currentUserProfile {
    nodeId
    id
    firstname
    lastname
    isAdmin
  }
}
    `;
/**
 * __useCurrentUserProfileQuery__
 *
 * To run a query within a React component, call `useCurrentUserProfileQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserProfileQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserProfileQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserProfileQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CurrentUserProfileDocument, options);
}
export function useCurrentUserProfileLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CurrentUserProfileDocument, options);
}
//# sourceMappingURL=index.js.map