/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {};
export var BinderVisibility;
(function (BinderVisibility) {
    BinderVisibility["Listed"] = "listed";
    BinderVisibility["Private"] = "private";
    BinderVisibility["Unlisted"] = "unlisted";
})(BinderVisibility || (BinderVisibility = {}));
export var CardCondition;
(function (CardCondition) {
    CardCondition["Excellent"] = "excellent";
    CardCondition["Good"] = "good";
    CardCondition["LightPlayed"] = "light_played";
    CardCondition["Mint"] = "mint";
    CardCondition["NearMint"] = "near_mint";
    CardCondition["Played"] = "played";
    CardCondition["Poor"] = "poor";
})(CardCondition || (CardCondition = {}));
export var CurrencyCode;
(function (CurrencyCode) {
    CurrencyCode["Eur"] = "EUR";
    CurrencyCode["Gbp"] = "GBP";
    CurrencyCode["Jpy"] = "JPY";
    CurrencyCode["Thb"] = "THB";
    CurrencyCode["Usd"] = "USD";
})(CurrencyCode || (CurrencyCode = {}));
export var FilterIs;
(function (FilterIs) {
    FilterIs["NotNull"] = "NOT_NULL";
    FilterIs["Null"] = "NULL";
})(FilterIs || (FilterIs = {}));
export var LanguageCode;
(function (LanguageCode) {
    LanguageCode["Ar"] = "ar";
    LanguageCode["De"] = "de";
    LanguageCode["En"] = "en";
    LanguageCode["Es"] = "es";
    LanguageCode["Fr"] = "fr";
    LanguageCode["Grc"] = "grc";
    LanguageCode["He"] = "he";
    LanguageCode["It"] = "it";
    LanguageCode["Ja"] = "ja";
    LanguageCode["Ko"] = "ko";
    LanguageCode["La"] = "la";
    LanguageCode["Ph"] = "ph";
    LanguageCode["Pt"] = "pt";
    LanguageCode["Qya"] = "qya";
    LanguageCode["Ru"] = "ru";
    LanguageCode["Sa"] = "sa";
    LanguageCode["Zhs"] = "zhs";
    LanguageCode["Zht"] = "zht";
})(LanguageCode || (LanguageCode = {}));
export var MarketPriceSource;
(function (MarketPriceSource) {
    MarketPriceSource["Cardkingdom"] = "cardkingdom";
    MarketPriceSource["Cardmarket"] = "cardmarket";
    MarketPriceSource["Tcgplayer"] = "tcgplayer";
})(MarketPriceSource || (MarketPriceSource = {}));
export var MtgColor;
(function (MtgColor) {
    MtgColor["B"] = "B";
    MtgColor["C"] = "C";
    MtgColor["G"] = "G";
    MtgColor["R"] = "R";
    MtgColor["U"] = "U";
    MtgColor["W"] = "W";
})(MtgColor || (MtgColor = {}));
/** Defines a per-field sorting order */
export var OrderByDirection;
(function (OrderByDirection) {
    /** Ascending order, nulls first */
    OrderByDirection["AscNullsFirst"] = "AscNullsFirst";
    /** Ascending order, nulls last */
    OrderByDirection["AscNullsLast"] = "AscNullsLast";
    /** Descending order, nulls first */
    OrderByDirection["DescNullsFirst"] = "DescNullsFirst";
    /** Descending order, nulls last */
    OrderByDirection["DescNullsLast"] = "DescNullsLast";
})(OrderByDirection || (OrderByDirection = {}));
export var OrganizationMemberRole;
(function (OrganizationMemberRole) {
    OrganizationMemberRole["Admin"] = "ADMIN";
    OrganizationMemberRole["Member"] = "MEMBER";
    OrganizationMemberRole["Owner"] = "OWNER";
})(OrganizationMemberRole || (OrganizationMemberRole = {}));
export const BinderCardSummaryFieldsFragmentDoc = gql `
    fragment BinderCardSummaryFields on BinderCards {
  id
  condition
  dynamicPriceRule
  finish
  language
  priceAmount
  priceCurrency
  quantity
  card {
    id
    name
    collectorNumber
    finishes
    imageNormalUrl
    imageSmallUrl
    releasedAt
    cardSet {
      code
      name
    }
    marketPrices(first: 12, orderBy: [{source: AscNullsLast}]) {
      edges {
        node {
          source
          finish
          amount
          currency
          buyUrl
        }
      }
    }
  }
}
    `;
export const BinderCardDetailFieldsFragmentDoc = gql `
    fragment BinderCardDetailFields on BinderCards {
  ...BinderCardSummaryFields
  card {
    mtgCardDetail {
      typeLine
      oracleText
    }
  }
}
    ${BinderCardSummaryFieldsFragmentDoc}`;
export const AddBinderCardDocument = gql `
    mutation AddBinderCard($binderId: UUID!, $tcgId: String!, $cardId: UUID!, $finish: String!, $position: Int!) {
  insertIntoBinderCardsCollection(
    objects: [{binderId: $binderId, tcgId: $tcgId, cardId: $cardId, finish: $finish, position: $position}]
  ) {
    records {
      id
      nodeId
    }
  }
}
    `;
/**
 * __useAddBinderCardMutation__
 *
 * To run a mutation, you first call `useAddBinderCardMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useAddBinderCardMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [addBinderCardMutation, { data, loading, error }] = useAddBinderCardMutation({
 *   variables: {
 *      binderId: // value for 'binderId'
 *      tcgId: // value for 'tcgId'
 *      cardId: // value for 'cardId'
 *      finish: // value for 'finish'
 *      position: // value for 'position'
 *   },
 * });
 */
export function useAddBinderCardMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(AddBinderCardDocument, options);
}
export const AddBinderCardsDocument = gql `
    mutation AddBinderCards($objects: [BinderCardsInsertInput!]!) {
  insertIntoBinderCardsCollection(objects: $objects) {
    records {
      id
      nodeId
    }
  }
}
    `;
/**
 * __useAddBinderCardsMutation__
 *
 * To run a mutation, you first call `useAddBinderCardsMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useAddBinderCardsMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [addBinderCardsMutation, { data, loading, error }] = useAddBinderCardsMutation({
 *   variables: {
 *      objects: // value for 'objects'
 *   },
 * });
 */
export function useAddBinderCardsMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(AddBinderCardsDocument, options);
}
export const BinderByShortIdDocument = gql `
    query BinderByShortId($shortId: String!, $cardFirst: Int!, $cardOffset: Int!, $cardOrderBy: [BinderCardsOrderBy!]!) {
  binderByShortId(binderShortId: $shortId) {
    id
    nodeId
    name
    note
    ownerId
    shortId
    tcgId
  }
  binderCardCountByShortId(binderShortId: $shortId)
  binderCardsByShortId(
    binderShortId: $shortId
    first: $cardFirst
    offset: $cardOffset
    orderBy: $cardOrderBy
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        ...BinderCardSummaryFields
      }
    }
  }
}
    ${BinderCardSummaryFieldsFragmentDoc}`;
/**
 * __useBinderByShortIdQuery__
 *
 * To run a query within a React component, call `useBinderByShortIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useBinderByShortIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBinderByShortIdQuery({
 *   variables: {
 *      shortId: // value for 'shortId'
 *      cardFirst: // value for 'cardFirst'
 *      cardOffset: // value for 'cardOffset'
 *      cardOrderBy: // value for 'cardOrderBy'
 *   },
 * });
 */
export function useBinderByShortIdQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(BinderByShortIdDocument, options);
}
export function useBinderByShortIdLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(BinderByShortIdDocument, options);
}
export const BinderCardDetailWindowDocument = gql `
    query BinderCardDetailWindow($shortId: String!, $cardFirst: Int!, $cardOffset: Int!, $cardOrderBy: [BinderCardsOrderBy!]!) {
  binderCardsByShortId(
    binderShortId: $shortId
    first: $cardFirst
    offset: $cardOffset
    orderBy: $cardOrderBy
  ) {
    edges {
      node {
        ...BinderCardDetailFields
      }
    }
  }
}
    ${BinderCardDetailFieldsFragmentDoc}`;
/**
 * __useBinderCardDetailWindowQuery__
 *
 * To run a query within a React component, call `useBinderCardDetailWindowQuery` and pass it any options that fit your needs.
 * When your component renders, `useBinderCardDetailWindowQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBinderCardDetailWindowQuery({
 *   variables: {
 *      shortId: // value for 'shortId'
 *      cardFirst: // value for 'cardFirst'
 *      cardOffset: // value for 'cardOffset'
 *      cardOrderBy: // value for 'cardOrderBy'
 *   },
 * });
 */
export function useBinderCardDetailWindowQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(BinderCardDetailWindowDocument, options);
}
export function useBinderCardDetailWindowLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(BinderCardDetailWindowDocument, options);
}
export const BinderCardVariantsDocument = gql `
    query BinderCardVariants($name: String!, $first: Int = 80) {
  cardsCollection(
    first: $first
    filter: {tcgId: {eq: "mtg"}, name: {eq: $name}}
    orderBy: [{releasedAt: DescNullsLast}, {collectorNumber: AscNullsLast}]
  ) {
    edges {
      node {
        id
        name
        collectorNumber
        finishes
        imageSmallUrl
        imageNormalUrl
        releasedAt
        cardSet {
          code
          name
        }
      }
    }
  }
}
    `;
/**
 * __useBinderCardVariantsQuery__
 *
 * To run a query within a React component, call `useBinderCardVariantsQuery` and pass it any options that fit your needs.
 * When your component renders, `useBinderCardVariantsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBinderCardVariantsQuery({
 *   variables: {
 *      name: // value for 'name'
 *      first: // value for 'first'
 *   },
 * });
 */
export function useBinderCardVariantsQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(BinderCardVariantsDocument, options);
}
export function useBinderCardVariantsLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(BinderCardVariantsDocument, options);
}
export const CardSearchDocument = gql `
    query CardSearch($query: String!, $first: Int = 8) {
  cardsCollection(
    first: $first
    filter: {tcgId: {eq: "mtg"}, name: {ilike: $query}}
    orderBy: [{releasedAt: DescNullsLast}, {name: AscNullsLast}]
  ) {
    edges {
      node {
        id
        externalId
        name
        collectorNumber
        rarity
        finishes
        imageSmallUrl
        imageNormalUrl
        releasedAt
        cardSet {
          id
          code
          name
          releaseAt
        }
        marketPrices(first: 8, orderBy: [{source: AscNullsLast}]) {
          edges {
            node {
              source
              finish
              amount
              currency
              priceDate
            }
          }
        }
      }
    }
  }
}
    `;
/**
 * __useCardSearchQuery__
 *
 * To run a query within a React component, call `useCardSearchQuery` and pass it any options that fit your needs.
 * When your component renders, `useCardSearchQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCardSearchQuery({
 *   variables: {
 *      query: // value for 'query'
 *      first: // value for 'first'
 *   },
 * });
 */
export function useCardSearchQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CardSearchDocument, options);
}
export function useCardSearchLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CardSearchDocument, options);
}
export const CardsForBinderImportDocument = gql `
    query CardsForBinderImport($filter: CardsFilter!, $first: Int!, $after: Cursor) {
  cardsCollection(first: $first, after: $after, filter: $filter) {
    edges {
      node {
        id
        externalId
        name
        collectorNumber
        finishes
        cardSet {
          code
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
    `;
/**
 * __useCardsForBinderImportQuery__
 *
 * To run a query within a React component, call `useCardsForBinderImportQuery` and pass it any options that fit your needs.
 * When your component renders, `useCardsForBinderImportQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCardsForBinderImportQuery({
 *   variables: {
 *      filter: // value for 'filter'
 *      first: // value for 'first'
 *      after: // value for 'after'
 *   },
 * });
 */
export function useCardsForBinderImportQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CardsForBinderImportDocument, options);
}
export function useCardsForBinderImportLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CardsForBinderImportDocument, options);
}
export const CreateBinderDocument = gql `
    mutation CreateBinder($name: String!, $tcgId: String = "mtg") {
  insertIntoBindersCollection(objects: [{name: $name, tcgId: $tcgId}]) {
    records {
      id
      nodeId
      name
      shortId
    }
  }
}
    `;
/**
 * __useCreateBinderMutation__
 *
 * To run a mutation, you first call `useCreateBinderMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateBinderMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createBinderMutation, { data, loading, error }] = useCreateBinderMutation({
 *   variables: {
 *      name: // value for 'name'
 *      tcgId: // value for 'tcgId'
 *   },
 * });
 */
export function useCreateBinderMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(CreateBinderDocument, options);
}
export const CurrentCurrencyRatesDocument = gql `
    query CurrentCurrencyRates {
  currencyRatesCollection(
    filter: {baseCurrency: {eq: USD}}
    orderBy: [{quoteCurrency: AscNullsLast}]
  ) {
    edges {
      node {
        quoteCurrency
        rate
      }
    }
  }
}
    `;
/**
 * __useCurrentCurrencyRatesQuery__
 *
 * To run a query within a React component, call `useCurrentCurrencyRatesQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentCurrencyRatesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentCurrencyRatesQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentCurrencyRatesQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CurrentCurrencyRatesDocument, options);
}
export function useCurrentCurrencyRatesLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CurrentCurrencyRatesDocument, options);
}
export const CurrentUserOrganizationContextsDocument = gql `
    query CurrentUserOrganizationContexts {
  currentUserOrganizationContexts {
    edges {
      node {
        organizationId
        role
        organization {
          id
          name
        }
      }
    }
  }
}
    `;
/**
 * __useCurrentUserOrganizationContextsQuery__
 *
 * To run a query within a React component, call `useCurrentUserOrganizationContextsQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserOrganizationContextsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserOrganizationContextsQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserOrganizationContextsQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CurrentUserOrganizationContextsDocument, options);
}
export function useCurrentUserOrganizationContextsLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CurrentUserOrganizationContextsDocument, options);
}
export const CurrentUserProfileDocument = gql `
    query CurrentUserProfile {
  currentUserProfile {
    nodeId
    id
    firstname
    lastname
    isAdmin
  }
}
    `;
/**
 * __useCurrentUserProfileQuery__
 *
 * To run a query within a React component, call `useCurrentUserProfileQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserProfileQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserProfileQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserProfileQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(CurrentUserProfileDocument, options);
}
export function useCurrentUserProfileLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(CurrentUserProfileDocument, options);
}
export const DeleteBinderCardDocument = gql `
    mutation DeleteBinderCard($id: UUID!) {
  deleteFromBinderCardsCollection(filter: {id: {eq: $id}}, atMost: 1) {
    affectedCount
  }
}
    `;
/**
 * __useDeleteBinderCardMutation__
 *
 * To run a mutation, you first call `useDeleteBinderCardMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteBinderCardMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteBinderCardMutation, { data, loading, error }] = useDeleteBinderCardMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useDeleteBinderCardMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(DeleteBinderCardDocument, options);
}
export const MyBindersDocument = gql `
    query MyBinders($ownerId: UUID!) {
  bindersCollection(
    filter: {ownerId: {eq: $ownerId}}
    orderBy: [{updatedAt: DescNullsLast}]
  ) {
    edges {
      node {
        id
        nodeId
        name
        shortId
        updatedAt
        binderCards(first: 1, orderBy: [{position: AscNullsLast}]) {
          edges {
            node {
              card {
                imageNormalUrl
                imageSmallUrl
              }
            }
          }
        }
      }
    }
  }
}
    `;
/**
 * __useMyBindersQuery__
 *
 * To run a query within a React component, call `useMyBindersQuery` and pass it any options that fit your needs.
 * When your component renders, `useMyBindersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMyBindersQuery({
 *   variables: {
 *      ownerId: // value for 'ownerId'
 *   },
 * });
 */
export function useMyBindersQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useQuery(MyBindersDocument, options);
}
export function useMyBindersLazyQuery(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useLazyQuery(MyBindersDocument, options);
}
export const RenameBinderDocument = gql `
    mutation RenameBinder($id: UUID!, $name: String!) {
  updateBindersCollection(filter: {id: {eq: $id}}, set: {name: $name}, atMost: 1) {
    affectedCount
    records {
      id
      name
    }
  }
}
    `;
/**
 * __useRenameBinderMutation__
 *
 * To run a mutation, you first call `useRenameBinderMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useRenameBinderMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [renameBinderMutation, { data, loading, error }] = useRenameBinderMutation({
 *   variables: {
 *      id: // value for 'id'
 *      name: // value for 'name'
 *   },
 * });
 */
export function useRenameBinderMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(RenameBinderDocument, options);
}
export const UpdateBinderCardDocument = gql `
    mutation UpdateBinderCard($id: UUID!, $set: BinderCardsUpdateInput!) {
  updateBinderCardsCollection(filter: {id: {eq: $id}}, set: $set, atMost: 1) {
    affectedCount
    records {
      ...BinderCardDetailFields
    }
  }
}
    ${BinderCardDetailFieldsFragmentDoc}`;
/**
 * __useUpdateBinderCardMutation__
 *
 * To run a mutation, you first call `useUpdateBinderCardMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateBinderCardMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateBinderCardMutation, { data, loading, error }] = useUpdateBinderCardMutation({
 *   variables: {
 *      id: // value for 'id'
 *      set: // value for 'set'
 *   },
 * });
 */
export function useUpdateBinderCardMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(UpdateBinderCardDocument, options);
}
export const UpdateBinderNoteDocument = gql `
    mutation UpdateBinderNote($id: UUID!, $note: String!) {
  updateBindersCollection(filter: {id: {eq: $id}}, set: {note: $note}, atMost: 1) {
    affectedCount
    records {
      id
      note
    }
  }
}
    `;
/**
 * __useUpdateBinderNoteMutation__
 *
 * To run a mutation, you first call `useUpdateBinderNoteMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateBinderNoteMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateBinderNoteMutation, { data, loading, error }] = useUpdateBinderNoteMutation({
 *   variables: {
 *      id: // value for 'id'
 *      note: // value for 'note'
 *   },
 * });
 */
export function useUpdateBinderNoteMutation(baseOptions) {
    const options = { ...defaultOptions, ...baseOptions };
    return Apollo.useMutation(UpdateBinderNoteDocument, options);
}
//# sourceMappingURL=index.js.map