/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  BigFloat: any;
  BigInt: any;
  Cursor: any;
  Date: any;
  Datetime: string;
  JSON: { [key: string]: any };
  Opaque: any;
  Time: any;
  UUID: any;
};


/** Boolean expression comparing fields on type "BigFloat" */
export type BigFloatFilter = {
  eq?: Maybe<Scalars['BigFloat']>;
  gt?: Maybe<Scalars['BigFloat']>;
  gte?: Maybe<Scalars['BigFloat']>;
  in?: Maybe<Array<Scalars['BigFloat']>>;
  is?: Maybe<FilterIs>;
  lt?: Maybe<Scalars['BigFloat']>;
  lte?: Maybe<Scalars['BigFloat']>;
  neq?: Maybe<Scalars['BigFloat']>;
};

/** Boolean expression comparing fields on type "BigFloatList" */
export type BigFloatListFilter = {
  containedBy?: Maybe<Array<Scalars['BigFloat']>>;
  contains?: Maybe<Array<Scalars['BigFloat']>>;
  eq?: Maybe<Array<Scalars['BigFloat']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['BigFloat']>>;
};


/** Boolean expression comparing fields on type "BigInt" */
export type BigIntFilter = {
  eq?: Maybe<Scalars['BigInt']>;
  gt?: Maybe<Scalars['BigInt']>;
  gte?: Maybe<Scalars['BigInt']>;
  in?: Maybe<Array<Scalars['BigInt']>>;
  is?: Maybe<FilterIs>;
  lt?: Maybe<Scalars['BigInt']>;
  lte?: Maybe<Scalars['BigInt']>;
  neq?: Maybe<Scalars['BigInt']>;
};

/** Boolean expression comparing fields on type "BigIntList" */
export type BigIntListFilter = {
  containedBy?: Maybe<Array<Scalars['BigInt']>>;
  contains?: Maybe<Array<Scalars['BigInt']>>;
  eq?: Maybe<Array<Scalars['BigInt']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['BigInt']>>;
};

export type BinderCards = Node & {
  __typename?: 'BinderCards';
  binder: Maybe<Binders>;
  binderId: Scalars['UUID'];
  card: Maybe<Cards>;
  cardId: Scalars['UUID'];
  condition: CardCondition;
  createdAt: Scalars['Datetime'];
  dynamicPriceRule: Maybe<Scalars['String']>;
  finish: Scalars['String'];
  id: Scalars['UUID'];
  language: LanguageCode;
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  note: Maybe<Scalars['String']>;
  position: Scalars['Int'];
  priceAmount: Maybe<Scalars['BigFloat']>;
  priceCurrency: Maybe<CurrencyCode>;
  quantity: Scalars['Int'];
  tcgId: Scalars['String'];
  updatedAt: Scalars['Datetime'];
};

export type BinderCardsConnection = {
  __typename?: 'BinderCardsConnection';
  edges: Array<BinderCardsEdge>;
  pageInfo: PageInfo;
};

export type BinderCardsDeleteResponse = {
  __typename?: 'BinderCardsDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<BinderCards>;
};

export type BinderCardsEdge = {
  __typename?: 'BinderCardsEdge';
  cursor: Scalars['String'];
  node: BinderCards;
};

export type BinderCardsFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<BinderCardsFilter>>;
  binderId?: Maybe<UuidFilter>;
  cardId?: Maybe<UuidFilter>;
  condition?: Maybe<CardConditionFilter>;
  createdAt?: Maybe<DatetimeFilter>;
  dynamicPriceRule?: Maybe<StringFilter>;
  finish?: Maybe<StringFilter>;
  id?: Maybe<UuidFilter>;
  language?: Maybe<LanguageCodeFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<BinderCardsFilter>;
  note?: Maybe<StringFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<BinderCardsFilter>>;
  position?: Maybe<IntFilter>;
  priceAmount?: Maybe<BigFloatFilter>;
  priceCurrency?: Maybe<CurrencyCodeFilter>;
  quantity?: Maybe<IntFilter>;
  tcgId?: Maybe<StringFilter>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type BinderCardsInsertInput = {
  binderId?: Maybe<Scalars['UUID']>;
  cardId?: Maybe<Scalars['UUID']>;
  condition?: Maybe<CardCondition>;
  createdAt?: Maybe<Scalars['Datetime']>;
  dynamicPriceRule?: Maybe<Scalars['String']>;
  finish?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  language?: Maybe<LanguageCode>;
  note?: Maybe<Scalars['String']>;
  position?: Maybe<Scalars['Int']>;
  priceAmount?: Maybe<Scalars['BigFloat']>;
  priceCurrency?: Maybe<CurrencyCode>;
  quantity?: Maybe<Scalars['Int']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type BinderCardsInsertResponse = {
  __typename?: 'BinderCardsInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<BinderCards>;
};

export type BinderCardsOrderBy = {
  binderId?: Maybe<OrderByDirection>;
  cardId?: Maybe<OrderByDirection>;
  condition?: Maybe<OrderByDirection>;
  createdAt?: Maybe<OrderByDirection>;
  dynamicPriceRule?: Maybe<OrderByDirection>;
  finish?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  language?: Maybe<OrderByDirection>;
  note?: Maybe<OrderByDirection>;
  position?: Maybe<OrderByDirection>;
  priceAmount?: Maybe<OrderByDirection>;
  priceCurrency?: Maybe<OrderByDirection>;
  quantity?: Maybe<OrderByDirection>;
  tcgId?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type BinderCardsUpdateInput = {
  binderId?: Maybe<Scalars['UUID']>;
  cardId?: Maybe<Scalars['UUID']>;
  condition?: Maybe<CardCondition>;
  createdAt?: Maybe<Scalars['Datetime']>;
  dynamicPriceRule?: Maybe<Scalars['String']>;
  finish?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  language?: Maybe<LanguageCode>;
  note?: Maybe<Scalars['String']>;
  position?: Maybe<Scalars['Int']>;
  priceAmount?: Maybe<Scalars['BigFloat']>;
  priceCurrency?: Maybe<CurrencyCode>;
  quantity?: Maybe<Scalars['Int']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type BinderCardsUpdateResponse = {
  __typename?: 'BinderCardsUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<BinderCards>;
};

export enum BinderVisibility {
  Listed = 'listed',
  Private = 'private',
  Unlisted = 'unlisted'
}

/** Boolean expression comparing fields on type "BinderVisibility" */
export type BinderVisibilityFilter = {
  eq?: Maybe<BinderVisibility>;
  in?: Maybe<Array<BinderVisibility>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<BinderVisibility>;
};

export type Binders = Node & {
  __typename?: 'Binders';
  binderCards: Maybe<BinderCardsConnection>;
  createdAt: Scalars['Datetime'];
  id: Scalars['UUID'];
  name: Scalars['String'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  ownerId: Scalars['UUID'];
  shortId: Scalars['String'];
  tcg: Maybe<Tcg>;
  tcgId: Scalars['String'];
  updatedAt: Scalars['Datetime'];
  visibility: BinderVisibility;
};


export type BindersBinderCardsArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<BinderCardsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<BinderCardsOrderBy>>;
};

export type BindersConnection = {
  __typename?: 'BindersConnection';
  edges: Array<BindersEdge>;
  pageInfo: PageInfo;
};

export type BindersDeleteResponse = {
  __typename?: 'BindersDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Binders>;
};

export type BindersEdge = {
  __typename?: 'BindersEdge';
  cursor: Scalars['String'];
  node: Binders;
};

export type BindersFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<BindersFilter>>;
  createdAt?: Maybe<DatetimeFilter>;
  id?: Maybe<UuidFilter>;
  name?: Maybe<StringFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<BindersFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<BindersFilter>>;
  ownerId?: Maybe<UuidFilter>;
  shortId?: Maybe<StringFilter>;
  tcgId?: Maybe<StringFilter>;
  updatedAt?: Maybe<DatetimeFilter>;
  visibility?: Maybe<BinderVisibilityFilter>;
};

export type BindersInsertInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['UUID']>;
  name?: Maybe<Scalars['String']>;
  ownerId?: Maybe<Scalars['UUID']>;
  shortId?: Maybe<Scalars['String']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
  visibility?: Maybe<BinderVisibility>;
};

export type BindersInsertResponse = {
  __typename?: 'BindersInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Binders>;
};

export type BindersOrderBy = {
  createdAt?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  name?: Maybe<OrderByDirection>;
  ownerId?: Maybe<OrderByDirection>;
  shortId?: Maybe<OrderByDirection>;
  tcgId?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
  visibility?: Maybe<OrderByDirection>;
};

export type BindersUpdateInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['UUID']>;
  name?: Maybe<Scalars['String']>;
  ownerId?: Maybe<Scalars['UUID']>;
  shortId?: Maybe<Scalars['String']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
  visibility?: Maybe<BinderVisibility>;
};

export type BindersUpdateResponse = {
  __typename?: 'BindersUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Binders>;
};

/** Boolean expression comparing fields on type "Boolean" */
export type BooleanFilter = {
  eq?: Maybe<Scalars['Boolean']>;
  is?: Maybe<FilterIs>;
};

/** Boolean expression comparing fields on type "BooleanList" */
export type BooleanListFilter = {
  containedBy?: Maybe<Array<Scalars['Boolean']>>;
  contains?: Maybe<Array<Scalars['Boolean']>>;
  eq?: Maybe<Array<Scalars['Boolean']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['Boolean']>>;
};

export enum CardCondition {
  Excellent = 'excellent',
  Good = 'good',
  LightPlayed = 'light_played',
  Mint = 'mint',
  NearMint = 'near_mint',
  Played = 'played',
  Poor = 'poor'
}

/** Boolean expression comparing fields on type "CardCondition" */
export type CardConditionFilter = {
  eq?: Maybe<CardCondition>;
  in?: Maybe<Array<CardCondition>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<CardCondition>;
};

export type CardMarketPrices = Node & {
  __typename?: 'CardMarketPrices';
  amount: Scalars['BigFloat'];
  buyUrl: Maybe<Scalars['String']>;
  card: Maybe<Cards>;
  cardId: Scalars['UUID'];
  createdAt: Scalars['Datetime'];
  currency: CurrencyCode;
  finish: Scalars['String'];
  id: Scalars['UUID'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  priceDate: Scalars['Date'];
  source: MarketPriceSource;
  tcgId: Scalars['String'];
  updatedAt: Scalars['Datetime'];
};

export type CardMarketPricesConnection = {
  __typename?: 'CardMarketPricesConnection';
  edges: Array<CardMarketPricesEdge>;
  pageInfo: PageInfo;
};

export type CardMarketPricesDeleteResponse = {
  __typename?: 'CardMarketPricesDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<CardMarketPrices>;
};

export type CardMarketPricesEdge = {
  __typename?: 'CardMarketPricesEdge';
  cursor: Scalars['String'];
  node: CardMarketPrices;
};

export type CardMarketPricesFilter = {
  amount?: Maybe<BigFloatFilter>;
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<CardMarketPricesFilter>>;
  buyUrl?: Maybe<StringFilter>;
  cardId?: Maybe<UuidFilter>;
  createdAt?: Maybe<DatetimeFilter>;
  currency?: Maybe<CurrencyCodeFilter>;
  finish?: Maybe<StringFilter>;
  id?: Maybe<UuidFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<CardMarketPricesFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<CardMarketPricesFilter>>;
  priceDate?: Maybe<DateFilter>;
  source?: Maybe<MarketPriceSourceFilter>;
  tcgId?: Maybe<StringFilter>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type CardMarketPricesInsertInput = {
  amount?: Maybe<Scalars['BigFloat']>;
  buyUrl?: Maybe<Scalars['String']>;
  cardId?: Maybe<Scalars['UUID']>;
  createdAt?: Maybe<Scalars['Datetime']>;
  currency?: Maybe<CurrencyCode>;
  finish?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  priceDate?: Maybe<Scalars['Date']>;
  source?: Maybe<MarketPriceSource>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type CardMarketPricesInsertResponse = {
  __typename?: 'CardMarketPricesInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<CardMarketPrices>;
};

export type CardMarketPricesOrderBy = {
  amount?: Maybe<OrderByDirection>;
  buyUrl?: Maybe<OrderByDirection>;
  cardId?: Maybe<OrderByDirection>;
  createdAt?: Maybe<OrderByDirection>;
  currency?: Maybe<OrderByDirection>;
  finish?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  priceDate?: Maybe<OrderByDirection>;
  source?: Maybe<OrderByDirection>;
  tcgId?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type CardMarketPricesUpdateInput = {
  amount?: Maybe<Scalars['BigFloat']>;
  buyUrl?: Maybe<Scalars['String']>;
  cardId?: Maybe<Scalars['UUID']>;
  createdAt?: Maybe<Scalars['Datetime']>;
  currency?: Maybe<CurrencyCode>;
  finish?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  priceDate?: Maybe<Scalars['Date']>;
  source?: Maybe<MarketPriceSource>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type CardMarketPricesUpdateResponse = {
  __typename?: 'CardMarketPricesUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<CardMarketPrices>;
};

export type CardSets = Node & {
  __typename?: 'CardSets';
  cards: Maybe<CardsConnection>;
  code: Maybe<Scalars['String']>;
  createdAt: Scalars['Datetime'];
  externalId: Scalars['String'];
  iconUrl: Maybe<Scalars['String']>;
  id: Scalars['UUID'];
  name: Scalars['String'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  releaseAt: Maybe<Scalars['Date']>;
  tcg: Maybe<Tcg>;
  tcgId: Scalars['String'];
  updatedAt: Scalars['Datetime'];
};


export type CardSetsCardsArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<CardsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<CardsOrderBy>>;
};

export type CardSetsConnection = {
  __typename?: 'CardSetsConnection';
  edges: Array<CardSetsEdge>;
  pageInfo: PageInfo;
};

export type CardSetsDeleteResponse = {
  __typename?: 'CardSetsDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<CardSets>;
};

export type CardSetsEdge = {
  __typename?: 'CardSetsEdge';
  cursor: Scalars['String'];
  node: CardSets;
};

export type CardSetsFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<CardSetsFilter>>;
  code?: Maybe<StringFilter>;
  createdAt?: Maybe<DatetimeFilter>;
  externalId?: Maybe<StringFilter>;
  iconUrl?: Maybe<StringFilter>;
  id?: Maybe<UuidFilter>;
  name?: Maybe<StringFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<CardSetsFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<CardSetsFilter>>;
  releaseAt?: Maybe<DateFilter>;
  tcgId?: Maybe<StringFilter>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type CardSetsInsertInput = {
  code?: Maybe<Scalars['String']>;
  createdAt?: Maybe<Scalars['Datetime']>;
  externalId?: Maybe<Scalars['String']>;
  iconUrl?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  name?: Maybe<Scalars['String']>;
  releaseAt?: Maybe<Scalars['Date']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type CardSetsInsertResponse = {
  __typename?: 'CardSetsInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<CardSets>;
};

export type CardSetsOrderBy = {
  code?: Maybe<OrderByDirection>;
  createdAt?: Maybe<OrderByDirection>;
  externalId?: Maybe<OrderByDirection>;
  iconUrl?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  name?: Maybe<OrderByDirection>;
  releaseAt?: Maybe<OrderByDirection>;
  tcgId?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type CardSetsUpdateInput = {
  code?: Maybe<Scalars['String']>;
  createdAt?: Maybe<Scalars['Datetime']>;
  externalId?: Maybe<Scalars['String']>;
  iconUrl?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  name?: Maybe<Scalars['String']>;
  releaseAt?: Maybe<Scalars['Date']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type CardSetsUpdateResponse = {
  __typename?: 'CardSetsUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<CardSets>;
};

export type Cards = Node & {
  __typename?: 'Cards';
  binderCards: Maybe<BinderCardsConnection>;
  cardSet: Maybe<CardSets>;
  cardSetId: Maybe<Scalars['UUID']>;
  collectorNumber: Maybe<Scalars['String']>;
  createdAt: Scalars['Datetime'];
  externalId: Scalars['String'];
  finishes: Array<Maybe<Scalars['String']>>;
  id: Scalars['UUID'];
  imageNormalUrl: Maybe<Scalars['String']>;
  imageSmallUrl: Maybe<Scalars['String']>;
  marketPrices: Maybe<CardMarketPricesConnection>;
  mtgCardDetail: Maybe<MtgCardDetails>;
  name: Scalars['String'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  rarity: Maybe<Scalars['String']>;
  releasedAt: Maybe<Scalars['Date']>;
  syncedAt: Maybe<Scalars['Datetime']>;
  tcg: Maybe<Tcg>;
  tcgId: Scalars['String'];
  updatedAt: Scalars['Datetime'];
};


export type CardsBinderCardsArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<BinderCardsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<BinderCardsOrderBy>>;
};


export type CardsMarketPricesArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<CardMarketPricesFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<CardMarketPricesOrderBy>>;
};

export type CardsConnection = {
  __typename?: 'CardsConnection';
  edges: Array<CardsEdge>;
  pageInfo: PageInfo;
};

export type CardsDeleteResponse = {
  __typename?: 'CardsDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Cards>;
};

export type CardsEdge = {
  __typename?: 'CardsEdge';
  cursor: Scalars['String'];
  node: Cards;
};

export type CardsFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<CardsFilter>>;
  cardSetId?: Maybe<UuidFilter>;
  collectorNumber?: Maybe<StringFilter>;
  createdAt?: Maybe<DatetimeFilter>;
  externalId?: Maybe<StringFilter>;
  finishes?: Maybe<StringListFilter>;
  id?: Maybe<UuidFilter>;
  imageNormalUrl?: Maybe<StringFilter>;
  imageSmallUrl?: Maybe<StringFilter>;
  name?: Maybe<StringFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<CardsFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<CardsFilter>>;
  rarity?: Maybe<StringFilter>;
  releasedAt?: Maybe<DateFilter>;
  syncedAt?: Maybe<DatetimeFilter>;
  tcgId?: Maybe<StringFilter>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type CardsInsertInput = {
  cardSetId?: Maybe<Scalars['UUID']>;
  collectorNumber?: Maybe<Scalars['String']>;
  createdAt?: Maybe<Scalars['Datetime']>;
  externalId?: Maybe<Scalars['String']>;
  finishes?: Maybe<Array<Maybe<Scalars['String']>>>;
  id?: Maybe<Scalars['UUID']>;
  imageNormalUrl?: Maybe<Scalars['String']>;
  imageSmallUrl?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  rarity?: Maybe<Scalars['String']>;
  releasedAt?: Maybe<Scalars['Date']>;
  syncedAt?: Maybe<Scalars['Datetime']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type CardsInsertResponse = {
  __typename?: 'CardsInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Cards>;
};

export type CardsOrderBy = {
  cardSetId?: Maybe<OrderByDirection>;
  collectorNumber?: Maybe<OrderByDirection>;
  createdAt?: Maybe<OrderByDirection>;
  externalId?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  imageNormalUrl?: Maybe<OrderByDirection>;
  imageSmallUrl?: Maybe<OrderByDirection>;
  name?: Maybe<OrderByDirection>;
  rarity?: Maybe<OrderByDirection>;
  releasedAt?: Maybe<OrderByDirection>;
  syncedAt?: Maybe<OrderByDirection>;
  tcgId?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type CardsUpdateInput = {
  cardSetId?: Maybe<Scalars['UUID']>;
  collectorNumber?: Maybe<Scalars['String']>;
  createdAt?: Maybe<Scalars['Datetime']>;
  externalId?: Maybe<Scalars['String']>;
  finishes?: Maybe<Array<Maybe<Scalars['String']>>>;
  id?: Maybe<Scalars['UUID']>;
  imageNormalUrl?: Maybe<Scalars['String']>;
  imageSmallUrl?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  rarity?: Maybe<Scalars['String']>;
  releasedAt?: Maybe<Scalars['Date']>;
  syncedAt?: Maybe<Scalars['Datetime']>;
  tcgId?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type CardsUpdateResponse = {
  __typename?: 'CardsUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Cards>;
};

export enum CurrencyCode {
  Eur = 'EUR',
  Gbp = 'GBP',
  Jpy = 'JPY',
  Thb = 'THB',
  Usd = 'USD'
}

/** Boolean expression comparing fields on type "CurrencyCode" */
export type CurrencyCodeFilter = {
  eq?: Maybe<CurrencyCode>;
  in?: Maybe<Array<CurrencyCode>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<CurrencyCode>;
};



/** Boolean expression comparing fields on type "Date" */
export type DateFilter = {
  eq?: Maybe<Scalars['Date']>;
  gt?: Maybe<Scalars['Date']>;
  gte?: Maybe<Scalars['Date']>;
  in?: Maybe<Array<Scalars['Date']>>;
  is?: Maybe<FilterIs>;
  lt?: Maybe<Scalars['Date']>;
  lte?: Maybe<Scalars['Date']>;
  neq?: Maybe<Scalars['Date']>;
};

/** Boolean expression comparing fields on type "DateList" */
export type DateListFilter = {
  containedBy?: Maybe<Array<Scalars['Date']>>;
  contains?: Maybe<Array<Scalars['Date']>>;
  eq?: Maybe<Array<Scalars['Date']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['Date']>>;
};


/** Boolean expression comparing fields on type "Datetime" */
export type DatetimeFilter = {
  eq?: Maybe<Scalars['Datetime']>;
  gt?: Maybe<Scalars['Datetime']>;
  gte?: Maybe<Scalars['Datetime']>;
  in?: Maybe<Array<Scalars['Datetime']>>;
  is?: Maybe<FilterIs>;
  lt?: Maybe<Scalars['Datetime']>;
  lte?: Maybe<Scalars['Datetime']>;
  neq?: Maybe<Scalars['Datetime']>;
};

/** Boolean expression comparing fields on type "DatetimeList" */
export type DatetimeListFilter = {
  containedBy?: Maybe<Array<Scalars['Datetime']>>;
  contains?: Maybe<Array<Scalars['Datetime']>>;
  eq?: Maybe<Array<Scalars['Datetime']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['Datetime']>>;
};

export enum FilterIs {
  NotNull = 'NOT_NULL',
  Null = 'NULL'
}

/** Boolean expression comparing fields on type "Float" */
export type FloatFilter = {
  eq?: Maybe<Scalars['Float']>;
  gt?: Maybe<Scalars['Float']>;
  gte?: Maybe<Scalars['Float']>;
  in?: Maybe<Array<Scalars['Float']>>;
  is?: Maybe<FilterIs>;
  lt?: Maybe<Scalars['Float']>;
  lte?: Maybe<Scalars['Float']>;
  neq?: Maybe<Scalars['Float']>;
};

/** Boolean expression comparing fields on type "FloatList" */
export type FloatListFilter = {
  containedBy?: Maybe<Array<Scalars['Float']>>;
  contains?: Maybe<Array<Scalars['Float']>>;
  eq?: Maybe<Array<Scalars['Float']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['Float']>>;
};

/** Boolean expression comparing fields on type "ID" */
export type IdFilter = {
  eq?: Maybe<Scalars['ID']>;
};

/** Boolean expression comparing fields on type "Int" */
export type IntFilter = {
  eq?: Maybe<Scalars['Int']>;
  gt?: Maybe<Scalars['Int']>;
  gte?: Maybe<Scalars['Int']>;
  in?: Maybe<Array<Scalars['Int']>>;
  is?: Maybe<FilterIs>;
  lt?: Maybe<Scalars['Int']>;
  lte?: Maybe<Scalars['Int']>;
  neq?: Maybe<Scalars['Int']>;
};

/** Boolean expression comparing fields on type "IntList" */
export type IntListFilter = {
  containedBy?: Maybe<Array<Scalars['Int']>>;
  contains?: Maybe<Array<Scalars['Int']>>;
  eq?: Maybe<Array<Scalars['Int']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['Int']>>;
};


export enum LanguageCode {
  Ar = 'ar',
  De = 'de',
  En = 'en',
  Es = 'es',
  Fr = 'fr',
  Grc = 'grc',
  He = 'he',
  It = 'it',
  Ja = 'ja',
  Ko = 'ko',
  La = 'la',
  Ph = 'ph',
  Pt = 'pt',
  Qya = 'qya',
  Ru = 'ru',
  Sa = 'sa',
  Zhs = 'zhs',
  Zht = 'zht'
}

/** Boolean expression comparing fields on type "LanguageCode" */
export type LanguageCodeFilter = {
  eq?: Maybe<LanguageCode>;
  in?: Maybe<Array<LanguageCode>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<LanguageCode>;
};

export enum MarketPriceSource {
  Cardkingdom = 'cardkingdom',
  Cardmarket = 'cardmarket',
  Tcgplayer = 'tcgplayer'
}

/** Boolean expression comparing fields on type "MarketPriceSource" */
export type MarketPriceSourceFilter = {
  eq?: Maybe<MarketPriceSource>;
  in?: Maybe<Array<MarketPriceSource>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<MarketPriceSource>;
};

export type MtgCardDetails = Node & {
  __typename?: 'MtgCardDetails';
  card: Maybe<Cards>;
  cardId: Scalars['UUID'];
  colorIdentity: Array<Maybe<MtgColor>>;
  colors: Array<Maybe<MtgColor>>;
  createdAt: Scalars['Datetime'];
  keywords: Array<Maybe<Scalars['String']>>;
  layout: Maybe<Scalars['String']>;
  manaCost: Maybe<Scalars['String']>;
  manaValue: Maybe<Scalars['BigFloat']>;
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  oracleId: Maybe<Scalars['String']>;
  oracleText: Maybe<Scalars['String']>;
  typeLine: Maybe<Scalars['String']>;
  updatedAt: Scalars['Datetime'];
};

export type MtgCardDetailsConnection = {
  __typename?: 'MtgCardDetailsConnection';
  edges: Array<MtgCardDetailsEdge>;
  pageInfo: PageInfo;
};

export type MtgCardDetailsDeleteResponse = {
  __typename?: 'MtgCardDetailsDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<MtgCardDetails>;
};

export type MtgCardDetailsEdge = {
  __typename?: 'MtgCardDetailsEdge';
  cursor: Scalars['String'];
  node: MtgCardDetails;
};

export type MtgCardDetailsFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<MtgCardDetailsFilter>>;
  cardId?: Maybe<UuidFilter>;
  createdAt?: Maybe<DatetimeFilter>;
  keywords?: Maybe<StringListFilter>;
  layout?: Maybe<StringFilter>;
  manaCost?: Maybe<StringFilter>;
  manaValue?: Maybe<BigFloatFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<MtgCardDetailsFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<MtgCardDetailsFilter>>;
  oracleId?: Maybe<StringFilter>;
  oracleText?: Maybe<StringFilter>;
  typeLine?: Maybe<StringFilter>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type MtgCardDetailsInsertInput = {
  cardId?: Maybe<Scalars['UUID']>;
  colorIdentity?: Maybe<Array<Maybe<MtgColor>>>;
  colors?: Maybe<Array<Maybe<MtgColor>>>;
  createdAt?: Maybe<Scalars['Datetime']>;
  keywords?: Maybe<Array<Maybe<Scalars['String']>>>;
  layout?: Maybe<Scalars['String']>;
  manaCost?: Maybe<Scalars['String']>;
  manaValue?: Maybe<Scalars['BigFloat']>;
  oracleId?: Maybe<Scalars['String']>;
  oracleText?: Maybe<Scalars['String']>;
  typeLine?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type MtgCardDetailsInsertResponse = {
  __typename?: 'MtgCardDetailsInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<MtgCardDetails>;
};

export type MtgCardDetailsOrderBy = {
  cardId?: Maybe<OrderByDirection>;
  createdAt?: Maybe<OrderByDirection>;
  layout?: Maybe<OrderByDirection>;
  manaCost?: Maybe<OrderByDirection>;
  manaValue?: Maybe<OrderByDirection>;
  oracleId?: Maybe<OrderByDirection>;
  oracleText?: Maybe<OrderByDirection>;
  typeLine?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type MtgCardDetailsUpdateInput = {
  cardId?: Maybe<Scalars['UUID']>;
  colorIdentity?: Maybe<Array<Maybe<MtgColor>>>;
  colors?: Maybe<Array<Maybe<MtgColor>>>;
  createdAt?: Maybe<Scalars['Datetime']>;
  keywords?: Maybe<Array<Maybe<Scalars['String']>>>;
  layout?: Maybe<Scalars['String']>;
  manaCost?: Maybe<Scalars['String']>;
  manaValue?: Maybe<Scalars['BigFloat']>;
  oracleId?: Maybe<Scalars['String']>;
  oracleText?: Maybe<Scalars['String']>;
  typeLine?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type MtgCardDetailsUpdateResponse = {
  __typename?: 'MtgCardDetailsUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<MtgCardDetails>;
};

export enum MtgColor {
  B = 'B',
  C = 'C',
  G = 'G',
  R = 'R',
  U = 'U',
  W = 'W'
}

/** Boolean expression comparing fields on type "MtgColor" */
export type MtgColorFilter = {
  eq?: Maybe<MtgColor>;
  in?: Maybe<Array<MtgColor>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<MtgColor>;
};

/** The root type for creating and mutating data */
export type Mutation = {
  __typename?: 'Mutation';
  createOrganization: Maybe<Organizations>;
  /** Deletes zero or more records from the `BinderCards` collection */
  deleteFromBinderCardsCollection: BinderCardsDeleteResponse;
  /** Deletes zero or more records from the `Binders` collection */
  deleteFromBindersCollection: BindersDeleteResponse;
  /** Deletes zero or more records from the `CardMarketPrices` collection */
  deleteFromCardMarketPricesCollection: CardMarketPricesDeleteResponse;
  /** Deletes zero or more records from the `CardSets` collection */
  deleteFromCardSetsCollection: CardSetsDeleteResponse;
  /** Deletes zero or more records from the `Cards` collection */
  deleteFromCardsCollection: CardsDeleteResponse;
  /** Deletes zero or more records from the `MtgCardDetails` collection */
  deleteFromMtgCardDetailsCollection: MtgCardDetailsDeleteResponse;
  /** Deletes zero or more records from the `OrganizationMembers` collection */
  deleteFromOrganizationMembersCollection: OrganizationMembersDeleteResponse;
  /** Deletes zero or more records from the `Organizations` collection */
  deleteFromOrganizationsCollection: OrganizationsDeleteResponse;
  /** Deletes zero or more records from the `Tcg` collection */
  deleteFromTcgCollection: TcgDeleteResponse;
  /** Deletes zero or more records from the `UserProfiles` collection */
  deleteFromUserProfilesCollection: UserProfilesDeleteResponse;
  /** Adds one or more `BinderCards` records to the collection */
  insertIntoBinderCardsCollection: Maybe<BinderCardsInsertResponse>;
  /** Adds one or more `Binders` records to the collection */
  insertIntoBindersCollection: Maybe<BindersInsertResponse>;
  /** Adds one or more `CardMarketPrices` records to the collection */
  insertIntoCardMarketPricesCollection: Maybe<CardMarketPricesInsertResponse>;
  /** Adds one or more `CardSets` records to the collection */
  insertIntoCardSetsCollection: Maybe<CardSetsInsertResponse>;
  /** Adds one or more `Cards` records to the collection */
  insertIntoCardsCollection: Maybe<CardsInsertResponse>;
  /** Adds one or more `MtgCardDetails` records to the collection */
  insertIntoMtgCardDetailsCollection: Maybe<MtgCardDetailsInsertResponse>;
  /** Adds one or more `OrganizationMembers` records to the collection */
  insertIntoOrganizationMembersCollection: Maybe<OrganizationMembersInsertResponse>;
  /** Adds one or more `Organizations` records to the collection */
  insertIntoOrganizationsCollection: Maybe<OrganizationsInsertResponse>;
  /** Adds one or more `Tcg` records to the collection */
  insertIntoTcgCollection: Maybe<TcgInsertResponse>;
  /** Adds one or more `UserProfiles` records to the collection */
  insertIntoUserProfilesCollection: Maybe<UserProfilesInsertResponse>;
  /** Updates zero or more records in the `BinderCards` collection */
  updateBinderCardsCollection: BinderCardsUpdateResponse;
  /** Updates zero or more records in the `Binders` collection */
  updateBindersCollection: BindersUpdateResponse;
  /** Updates zero or more records in the `CardMarketPrices` collection */
  updateCardMarketPricesCollection: CardMarketPricesUpdateResponse;
  /** Updates zero or more records in the `CardSets` collection */
  updateCardSetsCollection: CardSetsUpdateResponse;
  /** Updates zero or more records in the `Cards` collection */
  updateCardsCollection: CardsUpdateResponse;
  /** Updates zero or more records in the `MtgCardDetails` collection */
  updateMtgCardDetailsCollection: MtgCardDetailsUpdateResponse;
  /** Updates zero or more records in the `OrganizationMembers` collection */
  updateOrganizationMembersCollection: OrganizationMembersUpdateResponse;
  /** Updates zero or more records in the `Organizations` collection */
  updateOrganizationsCollection: OrganizationsUpdateResponse;
  /** Updates zero or more records in the `Tcg` collection */
  updateTcgCollection: TcgUpdateResponse;
  /** Updates zero or more records in the `UserProfiles` collection */
  updateUserProfilesCollection: UserProfilesUpdateResponse;
};


/** The root type for creating and mutating data */
export type MutationCreateOrganizationArgs = {
  name: Scalars['String'];
};


/** The root type for creating and mutating data */
export type MutationDeleteFromBinderCardsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<BinderCardsFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromBindersCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<BindersFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromCardMarketPricesCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<CardMarketPricesFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromCardSetsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<CardSetsFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromCardsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<CardsFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromMtgCardDetailsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<MtgCardDetailsFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromOrganizationMembersCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<OrganizationMembersFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromOrganizationsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<OrganizationsFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromTcgCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<TcgFilter>;
};


/** The root type for creating and mutating data */
export type MutationDeleteFromUserProfilesCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<UserProfilesFilter>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoBinderCardsCollectionArgs = {
  objects: Array<BinderCardsInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoBindersCollectionArgs = {
  objects: Array<BindersInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoCardMarketPricesCollectionArgs = {
  objects: Array<CardMarketPricesInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoCardSetsCollectionArgs = {
  objects: Array<CardSetsInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoCardsCollectionArgs = {
  objects: Array<CardsInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoMtgCardDetailsCollectionArgs = {
  objects: Array<MtgCardDetailsInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoOrganizationMembersCollectionArgs = {
  objects: Array<OrganizationMembersInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoOrganizationsCollectionArgs = {
  objects: Array<OrganizationsInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoTcgCollectionArgs = {
  objects: Array<TcgInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationInsertIntoUserProfilesCollectionArgs = {
  objects: Array<UserProfilesInsertInput>;
};


/** The root type for creating and mutating data */
export type MutationUpdateBinderCardsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<BinderCardsFilter>;
  set: BinderCardsUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateBindersCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<BindersFilter>;
  set: BindersUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateCardMarketPricesCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<CardMarketPricesFilter>;
  set: CardMarketPricesUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateCardSetsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<CardSetsFilter>;
  set: CardSetsUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateCardsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<CardsFilter>;
  set: CardsUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateMtgCardDetailsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<MtgCardDetailsFilter>;
  set: MtgCardDetailsUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateOrganizationMembersCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<OrganizationMembersFilter>;
  set: OrganizationMembersUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateOrganizationsCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<OrganizationsFilter>;
  set: OrganizationsUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateTcgCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<TcgFilter>;
  set: TcgUpdateInput;
};


/** The root type for creating and mutating data */
export type MutationUpdateUserProfilesCollectionArgs = {
  atMost?: Scalars['Int'];
  filter?: Maybe<UserProfilesFilter>;
  set: UserProfilesUpdateInput;
};

export type Node = {
  /** Retrieves a record by `ID` */
  nodeId: Scalars['ID'];
};


/** Boolean expression comparing fields on type "Opaque" */
export type OpaqueFilter = {
  eq?: Maybe<Scalars['Opaque']>;
  is?: Maybe<FilterIs>;
};

/** Defines a per-field sorting order */
export enum OrderByDirection {
  /** Ascending order, nulls first */
  AscNullsFirst = 'AscNullsFirst',
  /** Ascending order, nulls last */
  AscNullsLast = 'AscNullsLast',
  /** Descending order, nulls first */
  DescNullsFirst = 'DescNullsFirst',
  /** Descending order, nulls last */
  DescNullsLast = 'DescNullsLast'
}

export enum OrganizationMemberRole {
  Admin = 'ADMIN',
  Member = 'MEMBER',
  Owner = 'OWNER'
}

/** Boolean expression comparing fields on type "OrganizationMemberRole" */
export type OrganizationMemberRoleFilter = {
  eq?: Maybe<OrganizationMemberRole>;
  in?: Maybe<Array<OrganizationMemberRole>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<OrganizationMemberRole>;
};

export type OrganizationMembers = Node & {
  __typename?: 'OrganizationMembers';
  createdAt: Scalars['Datetime'];
  id: Scalars['UUID'];
  isActive: Scalars['Boolean'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  organization: Maybe<Organizations>;
  organizationId: Scalars['UUID'];
  role: OrganizationMemberRole;
  updatedAt: Scalars['Datetime'];
  userId: Scalars['UUID'];
};

export type OrganizationMembersConnection = {
  __typename?: 'OrganizationMembersConnection';
  edges: Array<OrganizationMembersEdge>;
  pageInfo: PageInfo;
};

export type OrganizationMembersDeleteResponse = {
  __typename?: 'OrganizationMembersDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<OrganizationMembers>;
};

export type OrganizationMembersEdge = {
  __typename?: 'OrganizationMembersEdge';
  cursor: Scalars['String'];
  node: OrganizationMembers;
};

export type OrganizationMembersFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<OrganizationMembersFilter>>;
  createdAt?: Maybe<DatetimeFilter>;
  id?: Maybe<UuidFilter>;
  isActive?: Maybe<BooleanFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<OrganizationMembersFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<OrganizationMembersFilter>>;
  organizationId?: Maybe<UuidFilter>;
  role?: Maybe<OrganizationMemberRoleFilter>;
  updatedAt?: Maybe<DatetimeFilter>;
  userId?: Maybe<UuidFilter>;
};

export type OrganizationMembersInsertInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['UUID']>;
  isActive?: Maybe<Scalars['Boolean']>;
  organizationId?: Maybe<Scalars['UUID']>;
  role?: Maybe<OrganizationMemberRole>;
  updatedAt?: Maybe<Scalars['Datetime']>;
  userId?: Maybe<Scalars['UUID']>;
};

export type OrganizationMembersInsertResponse = {
  __typename?: 'OrganizationMembersInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<OrganizationMembers>;
};

export type OrganizationMembersOrderBy = {
  createdAt?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  isActive?: Maybe<OrderByDirection>;
  organizationId?: Maybe<OrderByDirection>;
  role?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
  userId?: Maybe<OrderByDirection>;
};

export type OrganizationMembersUpdateInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['UUID']>;
  isActive?: Maybe<Scalars['Boolean']>;
  organizationId?: Maybe<Scalars['UUID']>;
  role?: Maybe<OrganizationMemberRole>;
  updatedAt?: Maybe<Scalars['Datetime']>;
  userId?: Maybe<Scalars['UUID']>;
};

export type OrganizationMembersUpdateResponse = {
  __typename?: 'OrganizationMembersUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<OrganizationMembers>;
};

export type Organizations = Node & {
  __typename?: 'Organizations';
  createdAt: Scalars['Datetime'];
  id: Scalars['UUID'];
  name: Scalars['String'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  organizationMembersCollection: Maybe<OrganizationMembersConnection>;
  updatedAt: Scalars['Datetime'];
};


export type OrganizationsOrganizationMembersCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<OrganizationMembersFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<OrganizationMembersOrderBy>>;
};

export type OrganizationsConnection = {
  __typename?: 'OrganizationsConnection';
  edges: Array<OrganizationsEdge>;
  pageInfo: PageInfo;
};

export type OrganizationsDeleteResponse = {
  __typename?: 'OrganizationsDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Organizations>;
};

export type OrganizationsEdge = {
  __typename?: 'OrganizationsEdge';
  cursor: Scalars['String'];
  node: Organizations;
};

export type OrganizationsFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<OrganizationsFilter>>;
  createdAt?: Maybe<DatetimeFilter>;
  id?: Maybe<UuidFilter>;
  name?: Maybe<StringFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<OrganizationsFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<OrganizationsFilter>>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type OrganizationsInsertInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['UUID']>;
  name?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type OrganizationsInsertResponse = {
  __typename?: 'OrganizationsInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Organizations>;
};

export type OrganizationsOrderBy = {
  createdAt?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  name?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type OrganizationsUpdateInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['UUID']>;
  name?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type OrganizationsUpdateResponse = {
  __typename?: 'OrganizationsUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Organizations>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  endCursor: Maybe<Scalars['String']>;
  hasNextPage: Scalars['Boolean'];
  hasPreviousPage: Scalars['Boolean'];
  startCursor: Maybe<Scalars['String']>;
};

/** The root type for querying data */
export type Query = {
  __typename?: 'Query';
  binderByShortId: Maybe<Binders>;
  binderCardsByShortId: Maybe<BinderCardsConnection>;
  /** A pagable collection of type `BinderCards` */
  binderCardsCollection: Maybe<BinderCardsConnection>;
  /** A pagable collection of type `Binders` */
  bindersCollection: Maybe<BindersConnection>;
  /** A pagable collection of type `CardMarketPrices` */
  cardMarketPricesCollection: Maybe<CardMarketPricesConnection>;
  /** A pagable collection of type `CardSets` */
  cardSetsCollection: Maybe<CardSetsConnection>;
  /** A pagable collection of type `Cards` */
  cardsCollection: Maybe<CardsConnection>;
  currentUserOrganizationContexts: Maybe<OrganizationMembersConnection>;
  currentUserProfile: Maybe<UserProfiles>;
  /** A pagable collection of type `MtgCardDetails` */
  mtgCardDetailsCollection: Maybe<MtgCardDetailsConnection>;
  /** Retrieve a record by its `ID` */
  node: Maybe<Node>;
  /** A pagable collection of type `OrganizationMembers` */
  organizationMembersCollection: Maybe<OrganizationMembersConnection>;
  /** A pagable collection of type `Organizations` */
  organizationsCollection: Maybe<OrganizationsConnection>;
  /** A pagable collection of type `Tcg` */
  tcgCollection: Maybe<TcgConnection>;
  /** A pagable collection of type `UserProfiles` */
  userProfilesCollection: Maybe<UserProfilesConnection>;
};


/** The root type for querying data */
export type QueryBinderByShortIdArgs = {
  binderShortId: Scalars['String'];
};


/** The root type for querying data */
export type QueryBinderCardsByShortIdArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  binderShortId: Scalars['String'];
  filter?: Maybe<BinderCardsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<BinderCardsOrderBy>>;
  resultLimit?: Maybe<Scalars['Int']>;
  sort?: Maybe<Scalars['String']>;
};


/** The root type for querying data */
export type QueryBinderCardsCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<BinderCardsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<BinderCardsOrderBy>>;
};


/** The root type for querying data */
export type QueryBindersCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<BindersFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<BindersOrderBy>>;
};


/** The root type for querying data */
export type QueryCardMarketPricesCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<CardMarketPricesFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<CardMarketPricesOrderBy>>;
};


/** The root type for querying data */
export type QueryCardSetsCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<CardSetsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<CardSetsOrderBy>>;
};


/** The root type for querying data */
export type QueryCardsCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<CardsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<CardsOrderBy>>;
};


/** The root type for querying data */
export type QueryCurrentUserOrganizationContextsArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<OrganizationMembersFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<OrganizationMembersOrderBy>>;
};


/** The root type for querying data */
export type QueryMtgCardDetailsCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<MtgCardDetailsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<MtgCardDetailsOrderBy>>;
};


/** The root type for querying data */
export type QueryNodeArgs = {
  nodeId: Scalars['ID'];
};


/** The root type for querying data */
export type QueryOrganizationMembersCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<OrganizationMembersFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<OrganizationMembersOrderBy>>;
};


/** The root type for querying data */
export type QueryOrganizationsCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<OrganizationsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<OrganizationsOrderBy>>;
};


/** The root type for querying data */
export type QueryTcgCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<TcgFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<TcgOrderBy>>;
};


/** The root type for querying data */
export type QueryUserProfilesCollectionArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<UserProfilesFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<UserProfilesOrderBy>>;
};

/** Boolean expression comparing fields on type "String" */
export type StringFilter = {
  eq?: Maybe<Scalars['String']>;
  gt?: Maybe<Scalars['String']>;
  gte?: Maybe<Scalars['String']>;
  ilike?: Maybe<Scalars['String']>;
  in?: Maybe<Array<Scalars['String']>>;
  iregex?: Maybe<Scalars['String']>;
  is?: Maybe<FilterIs>;
  like?: Maybe<Scalars['String']>;
  lt?: Maybe<Scalars['String']>;
  lte?: Maybe<Scalars['String']>;
  neq?: Maybe<Scalars['String']>;
  regex?: Maybe<Scalars['String']>;
  startsWith?: Maybe<Scalars['String']>;
};

/** Boolean expression comparing fields on type "StringList" */
export type StringListFilter = {
  containedBy?: Maybe<Array<Scalars['String']>>;
  contains?: Maybe<Array<Scalars['String']>>;
  eq?: Maybe<Array<Scalars['String']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['String']>>;
};

export type Tcg = Node & {
  __typename?: 'Tcg';
  binders: Maybe<BindersConnection>;
  cardSets: Maybe<CardSetsConnection>;
  cards: Maybe<CardsConnection>;
  createdAt: Scalars['Datetime'];
  id: Scalars['String'];
  name: Scalars['String'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  updatedAt: Scalars['Datetime'];
};


export type TcgBindersArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<BindersFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<BindersOrderBy>>;
};


export type TcgCardSetsArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<CardSetsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<CardSetsOrderBy>>;
};


export type TcgCardsArgs = {
  after?: Maybe<Scalars['Cursor']>;
  before?: Maybe<Scalars['Cursor']>;
  filter?: Maybe<CardsFilter>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
  offset?: Maybe<Scalars['Int']>;
  orderBy?: Maybe<Array<CardsOrderBy>>;
};

export type TcgConnection = {
  __typename?: 'TcgConnection';
  edges: Array<TcgEdge>;
  pageInfo: PageInfo;
};

export type TcgDeleteResponse = {
  __typename?: 'TcgDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Tcg>;
};

export type TcgEdge = {
  __typename?: 'TcgEdge';
  cursor: Scalars['String'];
  node: Tcg;
};

export type TcgFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<TcgFilter>>;
  createdAt?: Maybe<DatetimeFilter>;
  id?: Maybe<StringFilter>;
  name?: Maybe<StringFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<TcgFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<TcgFilter>>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type TcgInsertInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type TcgInsertResponse = {
  __typename?: 'TcgInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Tcg>;
};

export type TcgOrderBy = {
  createdAt?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  name?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type TcgUpdateInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  id?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type TcgUpdateResponse = {
  __typename?: 'TcgUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<Tcg>;
};


/** Boolean expression comparing fields on type "Time" */
export type TimeFilter = {
  eq?: Maybe<Scalars['Time']>;
  gt?: Maybe<Scalars['Time']>;
  gte?: Maybe<Scalars['Time']>;
  in?: Maybe<Array<Scalars['Time']>>;
  is?: Maybe<FilterIs>;
  lt?: Maybe<Scalars['Time']>;
  lte?: Maybe<Scalars['Time']>;
  neq?: Maybe<Scalars['Time']>;
};

/** Boolean expression comparing fields on type "TimeList" */
export type TimeListFilter = {
  containedBy?: Maybe<Array<Scalars['Time']>>;
  contains?: Maybe<Array<Scalars['Time']>>;
  eq?: Maybe<Array<Scalars['Time']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['Time']>>;
};


/** Boolean expression comparing fields on type "UUID" */
export type UuidFilter = {
  eq?: Maybe<Scalars['UUID']>;
  in?: Maybe<Array<Scalars['UUID']>>;
  is?: Maybe<FilterIs>;
  neq?: Maybe<Scalars['UUID']>;
};

/** Boolean expression comparing fields on type "UUIDList" */
export type UuidListFilter = {
  containedBy?: Maybe<Array<Scalars['UUID']>>;
  contains?: Maybe<Array<Scalars['UUID']>>;
  eq?: Maybe<Array<Scalars['UUID']>>;
  is?: Maybe<FilterIs>;
  overlaps?: Maybe<Array<Scalars['UUID']>>;
};

export type UserProfiles = Node & {
  __typename?: 'UserProfiles';
  createdAt: Scalars['Datetime'];
  firstname: Scalars['String'];
  id: Scalars['UUID'];
  isAdmin: Scalars['Boolean'];
  lastname: Scalars['String'];
  /** Globally Unique Record Identifier */
  nodeId: Scalars['ID'];
  updatedAt: Scalars['Datetime'];
};

export type UserProfilesConnection = {
  __typename?: 'UserProfilesConnection';
  edges: Array<UserProfilesEdge>;
  pageInfo: PageInfo;
};

export type UserProfilesDeleteResponse = {
  __typename?: 'UserProfilesDeleteResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<UserProfiles>;
};

export type UserProfilesEdge = {
  __typename?: 'UserProfilesEdge';
  cursor: Scalars['String'];
  node: UserProfiles;
};

export type UserProfilesFilter = {
  /** Returns true only if all its inner filters are true, otherwise returns false */
  and?: Maybe<Array<UserProfilesFilter>>;
  createdAt?: Maybe<DatetimeFilter>;
  firstname?: Maybe<StringFilter>;
  id?: Maybe<UuidFilter>;
  isAdmin?: Maybe<BooleanFilter>;
  lastname?: Maybe<StringFilter>;
  nodeId?: Maybe<IdFilter>;
  /** Negates a filter */
  not?: Maybe<UserProfilesFilter>;
  /** Returns true if at least one of its inner filters is true, otherwise returns false */
  or?: Maybe<Array<UserProfilesFilter>>;
  updatedAt?: Maybe<DatetimeFilter>;
};

export type UserProfilesInsertInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  firstname?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  isAdmin?: Maybe<Scalars['Boolean']>;
  lastname?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type UserProfilesInsertResponse = {
  __typename?: 'UserProfilesInsertResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<UserProfiles>;
};

export type UserProfilesOrderBy = {
  createdAt?: Maybe<OrderByDirection>;
  firstname?: Maybe<OrderByDirection>;
  id?: Maybe<OrderByDirection>;
  isAdmin?: Maybe<OrderByDirection>;
  lastname?: Maybe<OrderByDirection>;
  updatedAt?: Maybe<OrderByDirection>;
};

export type UserProfilesUpdateInput = {
  createdAt?: Maybe<Scalars['Datetime']>;
  firstname?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['UUID']>;
  isAdmin?: Maybe<Scalars['Boolean']>;
  lastname?: Maybe<Scalars['String']>;
  updatedAt?: Maybe<Scalars['Datetime']>;
};

export type UserProfilesUpdateResponse = {
  __typename?: 'UserProfilesUpdateResponse';
  /** Count of the records impacted by the mutation */
  affectedCount: Scalars['Int'];
  /** Array of records impacted by the mutation */
  records: Array<UserProfiles>;
};

export type AddBinderCardMutationVariables = Exact<{
  binderId: Scalars['UUID'];
  tcgId: Scalars['String'];
  cardId: Scalars['UUID'];
  finish: Scalars['String'];
  position: Scalars['Int'];
}>;


export type AddBinderCardMutation = (
  { __typename?: 'Mutation' }
  & { insertIntoBinderCardsCollection: Maybe<(
    { __typename?: 'BinderCardsInsertResponse' }
    & { records: Array<(
      { __typename?: 'BinderCards' }
      & Pick<BinderCards, 'id' | 'nodeId'>
    )> }
  )> }
);

export type BinderByShortIdQueryVariables = Exact<{
  shortId: Scalars['String'];
  cardSort: Scalars['String'];
  cardFirst: Scalars['Int'];
}>;


export type BinderByShortIdQuery = (
  { __typename?: 'Query' }
  & { binderByShortId: Maybe<(
    { __typename?: 'Binders' }
    & Pick<Binders, 'id' | 'nodeId' | 'name' | 'ownerId' | 'shortId' | 'tcgId'>
  )>, binderCardsByShortId: Maybe<(
    { __typename?: 'BinderCardsConnection' }
    & { pageInfo: (
      { __typename?: 'PageInfo' }
      & Pick<PageInfo, 'hasNextPage'>
    ), edges: Array<(
      { __typename?: 'BinderCardsEdge' }
      & { node: (
        { __typename?: 'BinderCards' }
        & Pick<BinderCards, 'id' | 'nodeId' | 'finish' | 'position' | 'quantity'>
        & { card: Maybe<(
          { __typename?: 'Cards' }
          & Pick<Cards, 'id' | 'name' | 'collectorNumber' | 'imageNormalUrl' | 'imageSmallUrl' | 'releasedAt'>
          & { cardSet: Maybe<(
            { __typename?: 'CardSets' }
            & Pick<CardSets, 'code' | 'name'>
          )> }
        )> }
      ) }
    )> }
  )> }
);

export type CardSearchQueryVariables = Exact<{
  query: Scalars['String'];
  first?: Maybe<Scalars['Int']>;
}>;


export type CardSearchQuery = (
  { __typename?: 'Query' }
  & { cardsCollection: Maybe<(
    { __typename?: 'CardsConnection' }
    & { edges: Array<(
      { __typename?: 'CardsEdge' }
      & { node: (
        { __typename?: 'Cards' }
        & Pick<Cards, 'id' | 'externalId' | 'name' | 'collectorNumber' | 'rarity' | 'finishes' | 'imageSmallUrl' | 'imageNormalUrl' | 'releasedAt'>
        & { cardSet: Maybe<(
          { __typename?: 'CardSets' }
          & Pick<CardSets, 'id' | 'code' | 'name' | 'releaseAt'>
        )>, marketPrices: Maybe<(
          { __typename?: 'CardMarketPricesConnection' }
          & { edges: Array<(
            { __typename?: 'CardMarketPricesEdge' }
            & { node: (
              { __typename?: 'CardMarketPrices' }
              & Pick<CardMarketPrices, 'source' | 'finish' | 'amount' | 'currency' | 'priceDate'>
            ) }
          )> }
        )> }
      ) }
    )> }
  )> }
);

export type CreateBinderMutationVariables = Exact<{
  name: Scalars['String'];
  tcgId?: Maybe<Scalars['String']>;
}>;


export type CreateBinderMutation = (
  { __typename?: 'Mutation' }
  & { insertIntoBindersCollection: Maybe<(
    { __typename?: 'BindersInsertResponse' }
    & { records: Array<(
      { __typename?: 'Binders' }
      & Pick<Binders, 'id' | 'nodeId' | 'name' | 'shortId'>
    )> }
  )> }
);

export type CurrentUserOrganizationContextsQueryVariables = Exact<{ [key: string]: never; }>;


export type CurrentUserOrganizationContextsQuery = (
  { __typename?: 'Query' }
  & { currentUserOrganizationContexts: Maybe<(
    { __typename?: 'OrganizationMembersConnection' }
    & { edges: Array<(
      { __typename?: 'OrganizationMembersEdge' }
      & { node: (
        { __typename?: 'OrganizationMembers' }
        & Pick<OrganizationMembers, 'organizationId' | 'role'>
        & { organization: Maybe<(
          { __typename?: 'Organizations' }
          & Pick<Organizations, 'id' | 'name'>
        )> }
      ) }
    )> }
  )> }
);

export type CurrentUserProfileQueryVariables = Exact<{ [key: string]: never; }>;


export type CurrentUserProfileQuery = (
  { __typename?: 'Query' }
  & { currentUserProfile: Maybe<(
    { __typename?: 'UserProfiles' }
    & Pick<UserProfiles, 'nodeId' | 'id' | 'firstname' | 'lastname' | 'isAdmin'>
  )> }
);

export type MyBindersQueryVariables = Exact<{
  ownerId: Scalars['UUID'];
}>;


export type MyBindersQuery = (
  { __typename?: 'Query' }
  & { bindersCollection: Maybe<(
    { __typename?: 'BindersConnection' }
    & { edges: Array<(
      { __typename?: 'BindersEdge' }
      & { node: (
        { __typename?: 'Binders' }
        & Pick<Binders, 'id' | 'nodeId' | 'name' | 'shortId' | 'updatedAt'>
        & { binderCards: Maybe<(
          { __typename?: 'BinderCardsConnection' }
          & { edges: Array<(
            { __typename?: 'BinderCardsEdge' }
            & { node: (
              { __typename?: 'BinderCards' }
              & { card: Maybe<(
                { __typename?: 'Cards' }
                & Pick<Cards, 'imageNormalUrl' | 'imageSmallUrl'>
              )> }
            ) }
          )> }
        )> }
      ) }
    )> }
  )> }
);


export const AddBinderCardDocument = gql`
    mutation AddBinderCard($binderId: UUID!, $tcgId: String!, $cardId: UUID!, $finish: String!, $position: Int!) {
  insertIntoBinderCardsCollection(
    objects: [{binderId: $binderId, tcgId: $tcgId, cardId: $cardId, finish: $finish, position: $position}]
  ) {
    records {
      id
      nodeId
    }
  }
}
    `;
export type AddBinderCardMutationFn = Apollo.MutationFunction<AddBinderCardMutation, AddBinderCardMutationVariables>;

/**
 * __useAddBinderCardMutation__
 *
 * To run a mutation, you first call `useAddBinderCardMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useAddBinderCardMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [addBinderCardMutation, { data, loading, error }] = useAddBinderCardMutation({
 *   variables: {
 *      binderId: // value for 'binderId'
 *      tcgId: // value for 'tcgId'
 *      cardId: // value for 'cardId'
 *      finish: // value for 'finish'
 *      position: // value for 'position'
 *   },
 * });
 */
export function useAddBinderCardMutation(baseOptions?: Apollo.MutationHookOptions<AddBinderCardMutation, AddBinderCardMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<AddBinderCardMutation, AddBinderCardMutationVariables>(AddBinderCardDocument, options);
      }
export type AddBinderCardMutationHookResult = ReturnType<typeof useAddBinderCardMutation>;
export type AddBinderCardMutationResult = Apollo.MutationResult<AddBinderCardMutation>;
export type AddBinderCardMutationOptions = Apollo.BaseMutationOptions<AddBinderCardMutation, AddBinderCardMutationVariables>;
export const BinderByShortIdDocument = gql`
    query BinderByShortId($shortId: String!, $cardSort: String!, $cardFirst: Int!) {
  binderByShortId(binderShortId: $shortId) {
    id
    nodeId
    name
    ownerId
    shortId
    tcgId
  }
  binderCardsByShortId(
    binderShortId: $shortId
    sort: $cardSort
    resultLimit: 500
    first: $cardFirst
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        id
        nodeId
        finish
        position
        quantity
        card {
          id
          name
          collectorNumber
          imageNormalUrl
          imageSmallUrl
          releasedAt
          cardSet {
            code
            name
          }
        }
      }
    }
  }
}
    `;

/**
 * __useBinderByShortIdQuery__
 *
 * To run a query within a React component, call `useBinderByShortIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useBinderByShortIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBinderByShortIdQuery({
 *   variables: {
 *      shortId: // value for 'shortId'
 *      cardSort: // value for 'cardSort'
 *      cardFirst: // value for 'cardFirst'
 *   },
 * });
 */
export function useBinderByShortIdQuery(baseOptions: Apollo.QueryHookOptions<BinderByShortIdQuery, BinderByShortIdQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<BinderByShortIdQuery, BinderByShortIdQueryVariables>(BinderByShortIdDocument, options);
      }
export function useBinderByShortIdLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<BinderByShortIdQuery, BinderByShortIdQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<BinderByShortIdQuery, BinderByShortIdQueryVariables>(BinderByShortIdDocument, options);
        }
export type BinderByShortIdQueryHookResult = ReturnType<typeof useBinderByShortIdQuery>;
export type BinderByShortIdLazyQueryHookResult = ReturnType<typeof useBinderByShortIdLazyQuery>;
export type BinderByShortIdQueryResult = Apollo.QueryResult<BinderByShortIdQuery, BinderByShortIdQueryVariables>;
export const CardSearchDocument = gql`
    query CardSearch($query: String!, $first: Int = 8) {
  cardsCollection(
    first: $first
    filter: {tcgId: {eq: "mtg"}, name: {ilike: $query}}
    orderBy: [{releasedAt: DescNullsLast}, {name: AscNullsLast}]
  ) {
    edges {
      node {
        id
        externalId
        name
        collectorNumber
        rarity
        finishes
        imageSmallUrl
        imageNormalUrl
        releasedAt
        cardSet {
          id
          code
          name
          releaseAt
        }
        marketPrices(first: 8, orderBy: [{source: AscNullsLast}]) {
          edges {
            node {
              source
              finish
              amount
              currency
              priceDate
            }
          }
        }
      }
    }
  }
}
    `;

/**
 * __useCardSearchQuery__
 *
 * To run a query within a React component, call `useCardSearchQuery` and pass it any options that fit your needs.
 * When your component renders, `useCardSearchQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCardSearchQuery({
 *   variables: {
 *      query: // value for 'query'
 *      first: // value for 'first'
 *   },
 * });
 */
export function useCardSearchQuery(baseOptions: Apollo.QueryHookOptions<CardSearchQuery, CardSearchQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CardSearchQuery, CardSearchQueryVariables>(CardSearchDocument, options);
      }
export function useCardSearchLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CardSearchQuery, CardSearchQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CardSearchQuery, CardSearchQueryVariables>(CardSearchDocument, options);
        }
export type CardSearchQueryHookResult = ReturnType<typeof useCardSearchQuery>;
export type CardSearchLazyQueryHookResult = ReturnType<typeof useCardSearchLazyQuery>;
export type CardSearchQueryResult = Apollo.QueryResult<CardSearchQuery, CardSearchQueryVariables>;
export const CreateBinderDocument = gql`
    mutation CreateBinder($name: String!, $tcgId: String = "mtg") {
  insertIntoBindersCollection(objects: [{name: $name, tcgId: $tcgId}]) {
    records {
      id
      nodeId
      name
      shortId
    }
  }
}
    `;
export type CreateBinderMutationFn = Apollo.MutationFunction<CreateBinderMutation, CreateBinderMutationVariables>;

/**
 * __useCreateBinderMutation__
 *
 * To run a mutation, you first call `useCreateBinderMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateBinderMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createBinderMutation, { data, loading, error }] = useCreateBinderMutation({
 *   variables: {
 *      name: // value for 'name'
 *      tcgId: // value for 'tcgId'
 *   },
 * });
 */
export function useCreateBinderMutation(baseOptions?: Apollo.MutationHookOptions<CreateBinderMutation, CreateBinderMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateBinderMutation, CreateBinderMutationVariables>(CreateBinderDocument, options);
      }
export type CreateBinderMutationHookResult = ReturnType<typeof useCreateBinderMutation>;
export type CreateBinderMutationResult = Apollo.MutationResult<CreateBinderMutation>;
export type CreateBinderMutationOptions = Apollo.BaseMutationOptions<CreateBinderMutation, CreateBinderMutationVariables>;
export const CurrentUserOrganizationContextsDocument = gql`
    query CurrentUserOrganizationContexts {
  currentUserOrganizationContexts {
    edges {
      node {
        organizationId
        role
        organization {
          id
          name
        }
      }
    }
  }
}
    `;

/**
 * __useCurrentUserOrganizationContextsQuery__
 *
 * To run a query within a React component, call `useCurrentUserOrganizationContextsQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserOrganizationContextsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserOrganizationContextsQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserOrganizationContextsQuery(baseOptions?: Apollo.QueryHookOptions<CurrentUserOrganizationContextsQuery, CurrentUserOrganizationContextsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CurrentUserOrganizationContextsQuery, CurrentUserOrganizationContextsQueryVariables>(CurrentUserOrganizationContextsDocument, options);
      }
export function useCurrentUserOrganizationContextsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CurrentUserOrganizationContextsQuery, CurrentUserOrganizationContextsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CurrentUserOrganizationContextsQuery, CurrentUserOrganizationContextsQueryVariables>(CurrentUserOrganizationContextsDocument, options);
        }
export type CurrentUserOrganizationContextsQueryHookResult = ReturnType<typeof useCurrentUserOrganizationContextsQuery>;
export type CurrentUserOrganizationContextsLazyQueryHookResult = ReturnType<typeof useCurrentUserOrganizationContextsLazyQuery>;
export type CurrentUserOrganizationContextsQueryResult = Apollo.QueryResult<CurrentUserOrganizationContextsQuery, CurrentUserOrganizationContextsQueryVariables>;
export const CurrentUserProfileDocument = gql`
    query CurrentUserProfile {
  currentUserProfile {
    nodeId
    id
    firstname
    lastname
    isAdmin
  }
}
    `;

/**
 * __useCurrentUserProfileQuery__
 *
 * To run a query within a React component, call `useCurrentUserProfileQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserProfileQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserProfileQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserProfileQuery(baseOptions?: Apollo.QueryHookOptions<CurrentUserProfileQuery, CurrentUserProfileQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CurrentUserProfileQuery, CurrentUserProfileQueryVariables>(CurrentUserProfileDocument, options);
      }
export function useCurrentUserProfileLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CurrentUserProfileQuery, CurrentUserProfileQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CurrentUserProfileQuery, CurrentUserProfileQueryVariables>(CurrentUserProfileDocument, options);
        }
export type CurrentUserProfileQueryHookResult = ReturnType<typeof useCurrentUserProfileQuery>;
export type CurrentUserProfileLazyQueryHookResult = ReturnType<typeof useCurrentUserProfileLazyQuery>;
export type CurrentUserProfileQueryResult = Apollo.QueryResult<CurrentUserProfileQuery, CurrentUserProfileQueryVariables>;
export const MyBindersDocument = gql`
    query MyBinders($ownerId: UUID!) {
  bindersCollection(
    filter: {ownerId: {eq: $ownerId}}
    orderBy: [{updatedAt: DescNullsLast}]
  ) {
    edges {
      node {
        id
        nodeId
        name
        shortId
        updatedAt
        binderCards(first: 1, orderBy: [{position: AscNullsLast}]) {
          edges {
            node {
              card {
                imageNormalUrl
                imageSmallUrl
              }
            }
          }
        }
      }
    }
  }
}
    `;

/**
 * __useMyBindersQuery__
 *
 * To run a query within a React component, call `useMyBindersQuery` and pass it any options that fit your needs.
 * When your component renders, `useMyBindersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMyBindersQuery({
 *   variables: {
 *      ownerId: // value for 'ownerId'
 *   },
 * });
 */
export function useMyBindersQuery(baseOptions: Apollo.QueryHookOptions<MyBindersQuery, MyBindersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MyBindersQuery, MyBindersQueryVariables>(MyBindersDocument, options);
      }
export function useMyBindersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MyBindersQuery, MyBindersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MyBindersQuery, MyBindersQueryVariables>(MyBindersDocument, options);
        }
export type MyBindersQueryHookResult = ReturnType<typeof useMyBindersQuery>;
export type MyBindersLazyQueryHookResult = ReturnType<typeof useMyBindersLazyQuery>;
export type MyBindersQueryResult = Apollo.QueryResult<MyBindersQuery, MyBindersQueryVariables>;